// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Entities.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Indoors")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfLoges")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Arenas", t =>
                        {
                            t.HasCheckConstraint("CHK_Arena_NumberOfLoges_NotNegative", "\"NumberOfLoges\" >= 0");

                            t.HasCheckConstraint("CHK_Arena_NumberOfSeats_NotNegative", "\"NumberOfSeats\" >= 0");
                        });
                });

            modelBuilder.Entity("Models.Entities.Base.BookableSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArenaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("EntranceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("EntranceId");

                    b.ToTable("BookableSpaces", t =>
                        {
                            t.HasCheckConstraint("CHK_BookableSpace_Price_NotNegative", "\"Price\" >= 0");
                        });

                    b.HasDiscriminator().HasValue("BookableSpace");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Models.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Models.Entities.Entrance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArenaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("VipEntrance")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.ToTable("Entrances");
                });

            modelBuilder.Entity("Models.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArenaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsFamilyFriendly")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfLogesToSell")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfSeatsToSell")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ReleaseTicketsDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.ToTable("Events", t =>
                        {
                            t.HasCheckConstraint("CHK_Event_Cost_NotNegative", "\"Cost\" >= 0");

                            t.HasCheckConstraint("CHK_Event_Date_InFuture", "\"Date\" > CURRENT_TIMESTAMP");

                            t.HasCheckConstraint("CHK_Event_EndTime_AfterStartTime", "\"EndTime\" > \"StartTime\"");

                            t.HasCheckConstraint("CHK_Event_HasSomethingToSell", "\"NumberOfSeatsToSell\" > 0 OR \"NumberOfLogesToSell\" > 0");

                            t.HasCheckConstraint("CHK_Event_NumberOfLogesToSell_NotNegative", "\"NumberOfLogesToSell\" >= 0");

                            t.HasCheckConstraint("CHK_Event_NumberOfSeatsToSell_NotNegative", "\"NumberOfSeatsToSell\" >= 0");

                            t.HasCheckConstraint("CHK_Event_Price_NotNegative", "\"Price\" >= 0");

                            t.HasCheckConstraint("CHK_Event_ReleaseTicketsDate_BeforeEventDate", "\"ReleaseTicketsDate\" < \"Date\"");
                        });
                });

            modelBuilder.Entity("Models.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Models.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookableSpaceId")
                        .HasColumnType("integer");

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookableSpaceId");

                    b.HasIndex("BookingId");

                    b.HasIndex("EventId", "BookableSpaceId")
                        .IsUnique();

                    b.ToTable("Tickets", t =>
                        {
                            t.HasCheckConstraint("CHK_Ticket_Price_NotNegative", "\"Price\" >= 0");
                        });
                });

            modelBuilder.Entity("Models.Entities.Loge", b =>
                {
                    b.HasBaseType("Models.Entities.Base.BookableSpace");

                    b.Property<string>("LogeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("integer");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CHK_BookableSpace_Price_NotNegative", "\"Price\" >= 0");

                            t.HasCheckConstraint("CHK_Loge_NumberOfPeople_NotNegative", "\"NumberOfPeople\" > 0");
                        });

                    b.HasDiscriminator().HasValue("Loge");
                });

            modelBuilder.Entity("Models.Entities.Seat", b =>
                {
                    b.HasBaseType("Models.Entities.Base.BookableSpace");

                    b.Property<int>("ColNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CHK_BookableSpace_Price_NotNegative", "\"Price\" >= 0");

                            t.HasCheckConstraint("CHK_Seat_ColNumber_NotNegative", "\"ColNumber\" >= 0");

                            t.HasCheckConstraint("CHK_Seat_RowNumber_NotNegative", "\"RowNumber\" >= 0");
                        });

                    b.HasDiscriminator().HasValue("Seat");
                });

            modelBuilder.Entity("Models.Entities.Base.BookableSpace", b =>
                {
                    b.HasOne("Models.Entities.Arena", "ArenaNavigation")
                        .WithMany("BookableSpacesNavigation")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Entrance", "EntranceNavigation")
                        .WithMany()
                        .HasForeignKey("EntranceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArenaNavigation");

                    b.Navigation("EntranceNavigation");
                });

            modelBuilder.Entity("Models.Entities.Entrance", b =>
                {
                    b.HasOne("Models.Entities.Arena", "ArenaNavigation")
                        .WithMany("EntrancesNavigation")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArenaNavigation");
                });

            modelBuilder.Entity("Models.Entities.Event", b =>
                {
                    b.HasOne("Models.Entities.Arena", "ArenaNavigation")
                        .WithMany("EventsNavigation")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArenaNavigation");
                });

            modelBuilder.Entity("Models.Entities.Payment", b =>
                {
                    b.HasOne("Models.Entities.Booking", "BookingNavigation")
                        .WithOne("PaymentNavigation")
                        .HasForeignKey("Models.Entities.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingNavigation");
                });

            modelBuilder.Entity("Models.Entities.Ticket", b =>
                {
                    b.HasOne("Models.Entities.Base.BookableSpace", "BookableSpaceNavigation")
                        .WithMany("TicketsNavigation")
                        .HasForeignKey("BookableSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Entities.Booking", "BookingNavigation")
                        .WithMany("TicketsNavigation")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Entities.Event", "EventNavigation")
                        .WithMany("TicketsNavigation")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookableSpaceNavigation");

                    b.Navigation("BookingNavigation");

                    b.Navigation("EventNavigation");
                });

            modelBuilder.Entity("Models.Entities.Arena", b =>
                {
                    b.Navigation("BookableSpacesNavigation");

                    b.Navigation("EntrancesNavigation");

                    b.Navigation("EventsNavigation");
                });

            modelBuilder.Entity("Models.Entities.Base.BookableSpace", b =>
                {
                    b.Navigation("TicketsNavigation");
                });

            modelBuilder.Entity("Models.Entities.Booking", b =>
                {
                    b.Navigation("PaymentNavigation");

                    b.Navigation("TicketsNavigation");
                });

            modelBuilder.Entity("Models.Entities.Event", b =>
                {
                    b.Navigation("TicketsNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
