@startuml

package "Web" {}
package "Models" {}
package "Application" {}
package "DataAccess" {}

Web --> Models
Web --> Application
Application --> Models
Application --> DataAccess
DataAccess --> Models

@enduml